// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnkmjjmowbmdljkepvqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indua21qam1vd2JtZGxqa2VwdnF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzUyMjAsImV4cCI6MjA1ODI1MTIyMH0.Ti8b2bPvSkzp0opR5SM__hnW51FQ-y17Ouvx5t2jKlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);